# Contents

- [3.1.1 예외처리 기능을 갖춘 DAO](#311-예외처리-기능을-갖춘-DAO)

# 3.1 다시 보는 초난감 DAO

## 3.1.1 예외처리 기능을 갖춘 DAO

`DB` 커넥션이라는 제한적인 리소스를 공유해 사용하는 서버에서 동작하는 `JDBC` 코드에서 반드시 지켜야 할 원칙이 있는데, 바로 `예외처리`가 그것이다.

### JDBC 수정 기능의 예외 처리 코드

```java
public class UserDao {
    // ...
    public void deleteAll() throws SQLException {
        Connection c = dataSource.getConnection();

        PreparedStatement ps = c.prepareStatement("delete from users");
        ps.executeUpdate();

        ps.close();
        c.close();
    }
    // ...
}
```

위의 코드는 현재까지 작성하였던 `UserDao`의 `deleteAll()` 메서드이다. 이 메서드는 `Connection`, `PreparedStatement` 두 개의 공유 리소스를 가져와서 사용하는데, 두 공유 리소스의 `close()` 메서드를 실행하기 전에 예외가 발생하면 공유 리소스가 제대로 반환되지 않을 수 있다.

일반적으로 서버에서는 제한된 개수의 `DB` 커넥션을 만들어서 재사용 가능한 풀로 관리한다. `DB` 풀은 매번 `getConnection()`으로 가져간 커넥션을 명시적으로 `close()` 메서드를 호출하여 반환해야만 다시 풀에 넣었다가 다음 커넥션 요청이 있을 때 재사용할 수 있다.

예외가 발생하여 반환되지 못한 `Connection`이 쌓이면 어느 순간 리소스가 부족하다는 오류를 내며 서버가 중단될 수 있다. 그런 의미에서 위의 코드는 다중 사용자를 위한 서버에 적용하기에는 치명적인 위험을 내포하고 있다.

그래서 `JDBC` 코드에서는 어떤 상황에서도 가져온 리소스를 반환하도록 `try/catch/finally` 구문 사용을 권장하고 있다.

```java
public class UserDao {
    // ...
    public void deleteAll() throws SQLException {
        Connection c = null;
        PreparedStatement ps = null;

        try {
            // 예외가 발생할 가능성이 있는 코드를 모두 try 블럭으로 묶는다.
            c = dataSource.getConnection();
            ps = c.prepareStatement("delete from users");
            ps.executeUpdate();
        } catch (SQLException e) {
            // 예외가 발생했을 때 부가작업을 위해 catch 블럭을 둔다.
            throw e;
        } finally {
            if (ps != null) {
                try {
                    ps.close();
                } catch (SQLException e) {
                    // ps.close() 메서드에서도 SQLException이 발생할 수 있으므로 try/catch를 적용해야 한다.
                }
            }
            if (c != null) {
                try {
                    c.close();
                } catch (SQLException e) {
                }
            }
        }

        ps.close();
        c.close();
    }
    // ...
}
```

위 코드는 기존의 `deleteAll()` 메서드에 `try/catch/finally` 구문을 적용한 것이다. `finally` 블럭 내의 코드는 `try` 블럭을 수행한 후에 정상적으로 처리되든 예외가 발생하든 상관없이 반드시 실행된다.

`try` 블럭으로 들어서면 반드시 `Connection`이나 `PreparedStatement`의 `close()` 메서드를 호출해서 리소스를 반환해야 한다. 그런데 문제는 예외가 어느 시점에 나는가에 따라서 `Connection`과 `PreparedStatement` 중 어느 것의 `close()` 메서드를 호출해야 할지가 달라진다는 점이다.

| 예외 발생 시점               | 예외 처리                                                                      |
| ---------------------------- | ------------------------------------------------------------------------------ |
| `dataSource.getConnection()` | `c`, `ps` 변수 모두 `null`이므로 `close()` 메서드를 호출하면 안 된다.          |
| `c.PreparedStatement`        | `c` 변수는 커넥션 객체를 가지므로 `c` 변수만 `close()` 메서드를 호출해야 한다. |
| `ps.executeUpdate()`         | `c`, `ps` 모두 `close()` 메서드를 호출해야 한다.                               |

위와 같이 `try` 블럭 내에서 예외가 어느 시점에 발생하느냐에 따라 예외처리가 다르다. 추가적인 문제로 `close()` 메서드도 `SQLException`이 발생할 수 있으므로 `try/catch` 문으로 처리해줘야 한다. `close()` 메서드가 실패했을 때는 특별히 해줄 수 있는 것이 없으므로 `catch` 블럭은 비어 있지만 로그를 남기는 등의 부가작업이 필요할 수 있으니 `catch` 블럭은 만들어 두는 것이 좋다.

### JDBC 조회 기능의 예외처리

조회를 위한 `JDBC` 코드는 좀 더 복잡한데, `ResultSet`이 추가되기 때문이다.

```java
public class UserDao {
    // ...
    public int getCount() throws SQLException {
        Connection c = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            c = dataSource.getConnection();
            ps = c.prepareStatement("select count(*) from users");
            rs = ps.executeQuery(); // ResultSet도 다양한 SQLException이 발생할 수 있는 코드이므로 try 블럭에 둔다.
            rs.next();
            return rs.getInt(1);
        } catch (SQLException e) {
            throw e;
        } finally {
            // 생성된 ResultSet을 닫아준다.
            // close()는 만들어진 순서의 반대로 하는 것이 원칙이다.
            if (rs != null) {
                try {
                    rs.close();
                } catch(SQLException e){
                }
            }
            if (ps != null) {
                try {
                    ps.close();
                } catch (SQLException e) {
                }
            }
            if (c != null) {
                try {
                    c.close();
                } catch (SQLException e) {
                }
            }
        }
    }
}
```

위의 코드는 `UserDao` 클래스의 `getCount()` 메서드에 `try/catch/finally` 구문을 적용한 것이다.
